[package]
name = "lemonlang"
version = "0.1.0"
edition = "2021"


[lib]
name = "lib"
path = "./src/lib/lib.rs"

[dependencies]
backtrace = "0.3.67"
clap = { version = "4.2.1", features = ["derive"] }
env_logger = "0.10.0"
log = "0.4.17"
test-log = "0.2.11"

